server:
  port: 7788

spring:
  application:
    name: config-server
  config:
    activate:
      on-profile:
        - active
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath: config/