server:
    port: 8090

spring:
  application:
    name: spring-learning
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 1995nian
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
